services:

  petrodb:
    container_name: petrodb_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DBNAME}
    user: 1000:1000
    ports:
      - "5432:5432"
    networks:
      - petrodb_net
    restart: unless-stopped
    volumes:
      - ./postgres-data:/data/postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "petrodb", "-U", "${DBUSER}" ]
      interval: 15s
      timeout: 10s
      retries: 3

  petroapi:
    container_name: petrodb_api
    image: ondrolexa/petroapi
    environment:
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      DBHOST: petrodb
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASSWORD: ${DBPASSWORD}
    depends_on:
      petrodb:
        condition: service_healthy
    ports:
      - "8000:80"
    networks:
      - petrodb_net
    restart: unless-stopped

networks:
  petrodb_net:
    driver: bridge
